### ISSUE TITLE
editor theme not switched

### ISSUE THREAD

**Issue by xgdgsc** [PaleoCrafter/Chronomorph#1]
I often see editor theme not switched, while the application theme switched after day / night time. After restart the theme is switched. I use latest goland/ pycharm professional and installed from the settings.

**Comment by xgdgsc** [comment]
I still see this in latest version

**Comment by xgdgsc** [comment]
I see the theme is switched inside settings but not effective, is it a bug of jetbrains itself?

**Comment by xgdgsc** [comment]
Now the settings aren' t getting saved.

**Comment by princed** [comment]
Fixed version — https://github.com/PaleoCrafter/Chronomorph/pull/7#issuecomment-617079807
