### ISSUE TITLE
Chronomorph forgets my configuration

### ISSUE THREAD

**Issue by Tuurlijk** [PaleoCrafter/Chronomorph#9]
After a restart of PHPStorm Cronomorph shows me an empty configuration.

PhpStorm 2020.1.1
Build #PS-201.7223.96, built on April 30, 2020

Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.6.11-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: run.processes.with.pty=TRUE, bigger.font.in.project.view=true, debugger.watches.in.variables=false, ide.tooltip.initialDelay=506
Non-Bundled Plugins: mobi.hsz.idea.gitignore, Scratch, Shifter, SVN Revision Graph, com.4lex4.intellij.solarized, com.fernandojimenez.obsidian.theme, com.intellij.ideolog, de.espend.idea.laravel, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, de.sandstormmedia.flowstorm, de.sgalinski.fluid.plugin.id, de.sgalinski.typoscript.enterprise.plugin.id, de.onigunn.intellij.xliff, de.thomasrosenau.diffplugin, io.paleocrafter.chronomorph, org.intellij.RegexpTester, BashSupport, ru.adelf.idea.dotenv, com.cedricziel.idea.typo3, org.toml.lang, some.awesome
Current Desktop: GNOME

**Comment by marvin-roesch** [comment]
Thanks for reporting this, @Tuurlijk! When upgrading to IntelliJ 2020, I only tested the basic functionality with changes based on fixed points in time. It looks like only the configuration options related to the daylight cycle are affected.
